name: Pull Request
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: install node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: jest
        run: yarn test
  testcontainers:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: install node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install dependencies
        run: yarn install
      - name: jest
        run: yarn test:testcontainers
