name: Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: compile
        run: yarn build
      - name: debug
        run: echo $GITHUB_EVENT_PATH && cat $GITHUB_EVENT_PATH
      - name: extract tag from github event payload
        run: |
          export TAG=`cat $GITHUB_EVENT_PATH | jq '.release.tag_name'`
          echo Will publish as version $TAG
          jq ".version = $TAG" package.json > package.json.tmp
          mv package.json.tmp package.json
      - name: NPM publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: push
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add package.json
          git commit -m "automatic version $TAG bump"
          git push origin HEAD:main
